
#? from 0 to 100 == males
#? from 101 to 201 == females
names=[
    "Rex","Reginald","Bernard","Bill","Jackie","Darrell","Harvey","Dean","Terrell","Donnie","Kelvin","Rick","Rafael","Shannon","Laurence","Sean","Jeremy","Evan","Pedro","Stewart","Bobby","Jonathan","Salvador","Marcus","Terrence","Oscar","Jan","Ralph","Daryl","Stephen","Alfonso","Ervin","Cecil","Ivan","Peter","Alton","Ben","Derek","Lee","Jeff","Tommie","Willis","Julian","Dave","Timmy","Gordon","Keith","Francis","Johnnie","Elijah","Frederick","Albert","Ramiro","Lawrence","Jesus","Mike","Tracy","Darrel","Adam","Cary","Randal","Van","Omar","Marshall","Alex","Wilbert","Charles","Moses","Jamie","Karl","Mark","Matt","Jacob","Clifton","Cedric","Jerry","Dustin","Clarence","Norman","Darnell","Milton","Marco","Leo","Gabriel","Kurt","Clayton","Alejandro","Angelo","Tommy","Manuel","Lewis","Eric","Earnest","Clifford","Kenneth","Allan","Darrin","Christopher","Felix","Armando","Darrin"
    ,"Shyann","Yareli","Taniya","Elsie","Arianna","Greta","Cristal","Zoe","Paulina","Kaylynn","Karma","Hazel","Tamia","Cecilia","Marin","Tia","Harmony","Alena","Stephany","Bethany","Angie","Raina","Mallory","Aiyana","Elisa","Marina","Desiree","Genevieve","Aliyah","Samantha","Jaylyn","Esmeralda","Johanna","Jaylee","Amelie","Yaretzi","Stacy","Julissa","Makaila","Abigayle","Brianna","Sophie","Jocelynn","Jadyn","Nathalie","Tanya","Sophia","Anabel","Annabella","Eva","Casey","Lisa","Katelynn","Kennedy","Isabela","Gwendolyn","Laila","Jakayla","Marley","Rylee","Salma","Angela","Aleah","Elise","Jaelynn","Jaliyah","Alexus","Kenzie","Karly","Alison","Ivy","Megan","Cheyanne","Jane","Belinda","Eileen","Jimena","Chloe","Aniya","Kaia","Sandra","Kaiya","Ireland","Jaslene","Alondra","Taylor","Giada","Phoenix","Michelle","Holly","Cherish","Alivia","Lilliana","Monserrat","Ansley","Lorelei","Katelyn","Haley","Renee","Reina","Zaria",
]

surnames = [
    "Davenport","Saunders","Gaines","Hull","Vaughn","Lowe","Stanton","Perez","Gilmore","Adams","Fitzpatrick","Landry","Mosley","Riddle","Dyer","Odonnell","Gillespie","Franco","Mcdowell","Mathis","Price","Sloan","Garner","Craig","Rosario","Bartlett","Farrell","Roach","Chandler","Mcintyre","Cox","Rubio","Pruitt","Bennett","Mcdaniel","Carter","Russo","Sandoval","Sexton","Riggs","Schroeder","Rich","Perry","Castro","Moon","Solomon","Shah","Valencia","Patton","Baker","Lane","Fields","Crane","Orr","Calhoun","Whitney","Friedman","Estes","Durham","Church","Bailey","Moss","Beck","Dorsey","Kent","Gibson","Soto","Carlson","Norman","Mcclain","Chan","Pace","Atkins","Guzman","Lucero","Watson","Garrison","Strickland","Bender","Mays","Fritz","Padilla","Huerta","Goodwin","Prince","Bruce","Nixon","Cruz","Ortiz","Dunn","Tran","Hart","Hicks","Smith","Jimenez","Tapia","Barr","Hardy","Fowler","Fox","Sweeney","Stephenson","Travis","Summers"
    ,"Long","Larsen","Spencer","Leon","Mueller","Stevenson","Roth","Reynolds","Waller","Strong","Alvarado","Acevedo","Delacruz","Christian","Solis","Tanner","Lee","Robles","Macias","Davies","Bradford","Kane","Harper","Parker","Wong","Payne","Stone","Duke","Glass","Bowers","Bryan","Leonard","Watts","Mccarthy","Marshall","Fuentes","Pitts","Waters","Dominguez","Shaw","Frazier","Sims","Andersen","Obrien","Moreno","Kaiser","Mccormick","Fleming","Monroe","Cline","Forbes","Shepherd","Barajas","Stephens","Nguyen","Costa","Richard","Harrington","Burch","Mason","Clay","Rivera","Johnson","Warren","Frederick","Dixon","Joseph","Gallagher","Merritt","Gordon","Cowan","Mcconnell","Ellis","May","Morrison","Holden","Callahan","Huff","Kemp","Brady","Mercado","Lambert","Curry","Butler","Carney","Benjamin","Stanley","King","Cantu","Mora","Roberson","Pena","Shields","Sutton","Richmond","Holmes","Clements","Gilmore"
]
